### ISSUE TITLE
Erro no Wordpress finder

### ISSUE THREAD

**Issue by snuckdev** [oppsec/Squid#1]
Quando vou checkar uma URL de Wordpress (peguei o blog da minha escola para exemplos, é cringe, eu sei) dá que o método websiteInformation is not defined, e de fato, analisando o código não achei nenhum método nomeado websiteInformation, só as suas chamadas.
https://github.com/oppsec/Squid/blob/355214be45ea5e7d14befcd798ae4b98526342c6/index.js#L82
https://github.com/oppsec/Squid/blob/355214be45ea5e7d14befcd798ae4b98526342c6/index.js#L85

```(node:14220) UnhandledPromiseRejectionWarning: ReferenceError: websiteInformation is not defined
    at getWordpressInfo (E:\JS\Squid\index.js:85:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by oppsec** [comment]
Obrigado por reportar, eu esqueci de atualizar o código pois estava arrumando outras coisas nele, no próximo push que eu der, provavelmente já estará arrumado isso.

**Comment by oppsec** [comment]
Desculpe-me pela demora, aparentemente o erro já foi arrumado, se puder verificar.
